#%RAML 0.8
version: v1.0
title: SDCD App

/login:
 post:
  responses: 
   200:
    body:
     application/json:

/users/create:
 post:
  responses: 
   200:
    body:
     application/json:
     
/users/read:
 post:
  responses: 
   200:
    body:
     application/json:
     
/users/read/count:
 post:
  responses: 
   200:
    body:
     application/json:

/users/update:
 post:
  responses: 
   200:
   
/users/update/password:
 post:
  responses: 
   200:

/users/delete:
 post:
  responses: 
   200:
   