#%RAML 0.8
version: v1.0
title: SDCD App

/login:
 post:
  responses: 
   200:
    body:
     application/json:

/users/create:
 post:
  responses: 
   200:
    body:
     application/json:
     
/users/read:
 post:
  responses: 
   200:
    body:
     application/json:
     
/users/read/count:
 post:
  responses: 
   200:
    body:
     application/json:

/users/update:
 post:
  responses: 
   200:
   
/users/update/password:
 post:
  responses: 
   200:

/users/delete:
 post:
  responses: 
   200:

/devices/service/reload:
 post:
  responses: 
   200:

/devices/create:
 post:
  responses: 
   200:
     
/devices/read:
 post:
  responses: 
   200:
    body:
     application/json:
     
/devices/read/count:
 post:
  responses: 
   200:
    body:
     application/json:

/devices/update:
 post:
  responses: 
   200:
   
/devices/update/password:
 post:
  responses: 
   200:

/devices/delete:
 post:
  responses: 
   200:
   
/features/update:
 post:
  responses: 
   200:

/features/read:
 post:
  responses: 
   200:
    body:
     application/json:

/features/read/enabled:
 post:
  responses: 
   200:
    body:
     application/json:

/archives/create:
 post:
  responses: 
   200:
    body:
     application/json:
     
/archives/read:
 post:
  responses: 
   200:
    body:
     application/json:
     
/archives/read/count:
 post:
  responses: 
   200:
    body:
     application/json:

/archives/read/single:
 post:
  responses: 
   200:
    body:
     application/json:

/archives/delete:
 post:
  responses: 
   200: